version: '3'
services:
    nginx:
        build:
            context: ./project/docker
            dockerfile: nginx.docker
        volumes:
            - ./project:/var/www/project
        ports:
            - "8081:80" 
    fpm:
        build:
            context: ./project/docker
            dockerfile: php-fpm.docker
        volumes:
            - ./project:/var/www/project
    cli:
        build:
            context: ./project/docker
            dockerfile: php-cli.docker
        volumes:
            - ./project:/var/www/project
        working_dir: /var/www
        tty: true